Do not modify permissions of cert parent directory if it already exists
juju-solutions/layer-tls-client pull request #23
Opened 2023-04-03 12:24 UTC by sudeephb

Fixes [lp:2009890](https://bugs.launchpad.net/filebeat-charm/+bug/2009890)

2023-04-03 12:35 UTC, esunar approved these changes

2023-04-03 12:50 UTC, canramesh approved these changes

2023-04-03 12:53 UTC, mkalcok requested changes
This change fixes the issue ([LP#2009890](https://bugs.launchpad.net/filebeat-charm/+bug/2009890)) only in cases when `/etc/ssl/certs` and `/etc/ssl/private` already exist. However problem will manifest again if `_ensure_directory` has to create these directories, because it'll set incorrect permissions again.

I think that proper solution is to add `mode` argument to the `_ensure_directory` with some sensible default, and then when we call this function to ensure that directory for certificates (line 148) and private keys (line 152) exist, we pass proper values (`0o755` and `0o710` respectively).

Now, what would be a sensible default for the `mode` argument? I'd say `0o755`, but that would change current default behavior, so perhaps using `0o770` as default isn't a worst thing when we allow user to specify otherwise.

2023-04-04 06:02 UTC, mkalcok approved these changes
Thanks for fixing this. It looks better now imo. I'm bit sad that this layer does not have a single test, but that's another issue.

2023-04-04 06:46 UTC, merged